### ISSUE TITLE
how to connect to mysql

### ISSUE THREAD

**Issue by geshan** [kasperisager/phpstack#11]
how do I connect to the mysql host?

**Comment by kasperisager** [comment]
From within the Nginx container?

**Comment by kasperisager** [comment]
Either way, I left the bit about container linking out of the instructions as it's covered by the Docker docs: http://docs.docker.com/userguide/dockerlinks/.

All other containers (MySQL, MongoDB, etc.) are now linked to the front container by default (a61011ac56feb0ee83e61e7b42e430645a90b60d). This means that if you wanted to connect to something like MySQL from within the front container you'd simply specify `mysql` as the host, e.g. `mysql://mysql:3306/your-db`

**Comment by geshan** [comment]
thanks.

**Comment by kasperisager** [comment]
No problem! Let me know if it works out.
