### ISSUE TITLE
mcrypt not enabled by default

### ISSUE THREAD

**Issue by approached** [kasperisager/phpstack#12]
Hi,

the mcrypt is not enabled by default. 

```
For checking which mods are enabled:
php -m

Enable:
php5enmod mcrypt
```

Can you add this?

**Comment by kasperisager** [comment]
Feel free to go crazy with the `php.ini` config: https://github.com/kasperisager/phpstack/blob/master/images/nginx/php.ini

**Comment by approached** [comment]
I just added... extension=mcrypt.so
It worked well. Thanks
