### ISSUE TITLE
Stuck somewhere at mongodb level

### ISSUE THREAD

**Issue by alihalabyah** [kasperisager/phpstack#13]
mongodb_1       | 2015-02-06T13:48:53.620+0000 [clientcursormon]  connections:0

**Comment by approached** [comment]
maybe i have the same problem... https://github.com/tutumcloud/tutum-docker-mongodb/issues/9

**Comment by kasperisager** [comment]
That's entirely normal; when running `fig up` you're attached to the logging output of all the containers. You may instead want to do a `fig start` which runs the containers in the background.
