### ISSUE TITLE
Shipyard not running?

### ISSUE THREAD

**Issue by joshuataylor** [kasperisager/phpstack#17]
Hi,

I'm running docker natively, not through a VM such as CoreOS or using Virtualbox.

So I've run the commands, and can see the phpinfo page on http://127.0.0.1, but can't see Shipyard on http://127.0.0.1:8080?

**Comment by joshuataylor** [comment]
I'm an idiot.

**Comment by alastairparagas** [comment]
@joshuataylor How did you solve this problem? I am stuck, and quite the Docker newbie.
